# QMTECH Wukong XC7A100T — Vivado XDC Constraints
# Church Machine top-level: ChurchWukongXC7A100T
#
# Toolchain: Vivado 2020.x+  (or Yosys + nextpnr-xilinx for open-source flow)
# Top module: top  (generated by Amaranth gen_verilog)
#
# Pin reference: QMTECH Wukong Board schematic v1.1
# --------------------------------------------------------------------------

# ── Clock ──────────────────────────────────────────────────────────────────
# 50 MHz oscillator on W19.  The Amaranth top instantiates an MMCM to
# produce the 100 MHz system clock; clk_in is the raw 50 MHz input.
set_property PACKAGE_PIN W19 [get_ports clk_in]
set_property IOSTANDARD  LVCMOS33 [get_ports clk_in]
create_clock -period 20.000 -name clk_in [get_ports clk_in]

# ── UART (PMOD J1, pins 1/2 — 3.3 V) ─────────────────────────────────────
# Connect a USB-UART adapter: TX board→host, RX host→board.
set_property PACKAGE_PIN H17 [get_ports uart_tx]
set_property IOSTANDARD  LVCMOS33 [get_ports uart_tx]

set_property PACKAGE_PIN G17 [get_ports uart_rx]
set_property IOSTANDARD  LVCMOS33 [get_ports uart_rx]

# ── User LEDs (active-LOW — drive low to illuminate) ──────────────────────
# The Amaranth logic drives led[i]=1 to mean ON; invert here.
set_property PACKAGE_PIN M26 [get_ports {led[0]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {led[0]}]

set_property PACKAGE_PIN N26 [get_ports {led[1]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {led[1]}]

set_property PACKAGE_PIN P26 [get_ports {led[2]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {led[2]}]

set_property PACKAGE_PIN P25 [get_ports {led[3]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {led[3]}]

# Active-LOW inversion for all four LEDs
set_property DRIVE 8 [get_ports {led[*]}]
set_property SLEW  SLOW [get_ports {led[*]}]

# ── Push button KEY1 (active-LOW, internal pull-up) ───────────────────────
set_property PACKAGE_PIN P16 [get_ports push_button]
set_property IOSTANDARD  LVCMOS33 [get_ports push_button]
set_property PULLUP true [get_ports push_button]

# ── Timing constraints ─────────────────────────────────────────────────────
# 100 MHz system clock generated by MMCM from 50 MHz clk_in.
# The MMCM output constraint is set automatically by Vivado when the MMCM
# primitive is instantiated with CLKOUT0_PERIOD=10.0 (see wukong_xc7a100t.tcl).
# Input/output false paths for UART and LEDs (slow async paths):
set_false_path -to [get_ports {uart_tx led[*]}]
set_false_path -from [get_ports {uart_rx push_button}]

# ── Ethernet RMII (LAN8720A or compatible PHY) ────────────────────────────
# PHY connected to Artix-7 bank 34 (VCCO = 3.3 V, LVCMOS33).
# Pin assignments from QMTECH Wukong board schematic v1.1, Ethernet section.
# The PHY provides a 50 MHz reference clock on rmii_ref_clk; constrain as
# an input clock for static timing analysis.
set_property PACKAGE_PIN W12 [get_ports rmii_ref_clk]
set_property IOSTANDARD  LVCMOS33 [get_ports rmii_ref_clk]
create_clock -period 20.000 -name rmii_ref_clk [get_ports rmii_ref_clk]

set_property PACKAGE_PIN AA11 [get_ports rmii_crs_dv]
set_property IOSTANDARD  LVCMOS33 [get_ports rmii_crs_dv]

set_property PACKAGE_PIN Y11 [get_ports {rmii_rxd[0]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {rmii_rxd[0]}]

set_property PACKAGE_PIN Y12 [get_ports {rmii_rxd[1]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {rmii_rxd[1]}]

set_property PACKAGE_PIN V11 [get_ports rmii_txen]
set_property IOSTANDARD  LVCMOS33 [get_ports rmii_txen]

set_property PACKAGE_PIN V12 [get_ports {rmii_txd[0]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {rmii_txd[0]}]

set_property PACKAGE_PIN W11 [get_ports {rmii_txd[1]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {rmii_txd[1]}]

set_property PACKAGE_PIN U10 [get_ports rmii_nrst]
set_property IOSTANDARD  LVCMOS33 [get_ports rmii_nrst]

# eth_irq — Ethernet RX-ready interrupt output.
# Routed to PMOD J3 pin 10 (H16) for debug probing; tie to interrupt
# controller input in the Tcl integration script when not probing.
set_property PACKAGE_PIN H16 [get_ports eth_irq]
set_property IOSTANDARD  LVCMOS33 [get_ports eth_irq]

# RMII input timing: the PHY outputs data synchronous to rmii_ref_clk
# with setup/hold margins of 4 ns / 2 ns (LAN8720A datasheet).
set_input_delay  -clock rmii_ref_clk -max  4.0 [get_ports {rmii_crs_dv rmii_rxd[*]}]
set_input_delay  -clock rmii_ref_clk -min  0.5 [get_ports {rmii_crs_dv rmii_rxd[*]}]

# RMII output timing: PHY latches data on rising rmii_ref_clk.
set_output_delay -clock rmii_ref_clk -max  4.0 [get_ports {rmii_txen rmii_txd[*]}]
set_output_delay -clock rmii_ref_clk -min -1.0 [get_ports {rmii_txen rmii_txd[*]}]

# PHY reset is asynchronous (driven LOW for ≥1 ms after power-up).
set_false_path -to [get_ports rmii_nrst]

# eth_irq is level-sensitive async to the system clock.
set_false_path -from [get_pins -hierarchical -filter {NAME =~ */rx_ready_reg/Q}] \
               -to   [get_ports eth_irq]

# ── Configuration ──────────────────────────────────────────────────────────
set_property CFGBVS         VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3  [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
