# QMTECH Wukong XC7A100T — Vivado XDC Constraints
# Church Machine top-level: ChurchWukongXC7A100T
#
# Toolchain: Vivado 2020.x+  (or Yosys + nextpnr-xilinx for open-source flow)
# Top module: top  (generated by Amaranth gen_verilog)
#
# Pin reference: QMTECH Wukong Board schematic v1.1
# --------------------------------------------------------------------------

# ── Clock ──────────────────────────────────────────────────────────────────
# 50 MHz oscillator on W19.  The Amaranth top instantiates an MMCM to
# produce the 100 MHz system clock; clk_in is the raw 50 MHz input.
set_property PACKAGE_PIN W19 [get_ports clk_in]
set_property IOSTANDARD  LVCMOS33 [get_ports clk_in]
create_clock -period 20.000 -name clk_in [get_ports clk_in]

# ── UART (PMOD J1, pins 1/2 — 3.3 V) ─────────────────────────────────────
# Connect a USB-UART adapter: TX board→host, RX host→board.
set_property PACKAGE_PIN H17 [get_ports uart_tx]
set_property IOSTANDARD  LVCMOS33 [get_ports uart_tx]

set_property PACKAGE_PIN G17 [get_ports uart_rx]
set_property IOSTANDARD  LVCMOS33 [get_ports uart_rx]

# ── User LEDs (active-LOW — drive low to illuminate) ──────────────────────
# The Amaranth logic drives led[i]=1 to mean ON; invert here.
set_property PACKAGE_PIN M26 [get_ports {led[0]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {led[0]}]

set_property PACKAGE_PIN N26 [get_ports {led[1]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {led[1]}]

set_property PACKAGE_PIN P26 [get_ports {led[2]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {led[2]}]

set_property PACKAGE_PIN P25 [get_ports {led[3]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {led[3]}]

# Active-LOW inversion for all four LEDs
set_property DRIVE 8 [get_ports {led[*]}]
set_property SLEW  SLOW [get_ports {led[*]}]

# ── Push button KEY1 (active-LOW, internal pull-up) ───────────────────────
set_property PACKAGE_PIN P16 [get_ports push_button]
set_property IOSTANDARD  LVCMOS33 [get_ports push_button]
set_property PULLUP true [get_ports push_button]

# ── Timing constraints ─────────────────────────────────────────────────────
# 100 MHz system clock generated by MMCM from 50 MHz clk_in.
# The MMCM output constraint is set automatically by Vivado when the MMCM
# primitive is instantiated with CLKOUT0_PERIOD=10.0 (see wukong_xc7a100t.tcl).
# Input/output false paths for UART and LEDs (slow async paths):
set_false_path -to [get_ports {uart_tx led[*]}]
set_false_path -from [get_ports {uart_rx push_button}]

# ── Configuration ──────────────────────────────────────────────────────────
set_property CFGBVS         VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3  [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
