# wukong_xc7a100t.tcl — Vivado project creation script for Church Machine
#
# Usage (from project root):
#   vivado -mode batch -source hardware/wukong_xc7a100t.tcl
#
# Requires:
#   build/church_wukong_xc7a100t.v  (generated by gen_verilog.py)
#   hardware/wukong_xc7a100t.xdc
#
# Output: vivado_wukong/church_wukong_xc7a100t.bit

set PROJ_NAME church_wukong_xc7a100t
set PART      xc7a100tfgg676-1
set OUTDIR    vivado_wukong
set TOPV      build/church_wukong_xc7a100t.v
set XDC       hardware/wukong_xc7a100t.xdc

file mkdir $OUTDIR

create_project $PROJ_NAME $OUTDIR -part $PART -force

add_files -norecurse $TOPV
add_files -fileset constrs_1 -norecurse $XDC

set_property top top [current_fileset]

# MMCM primitive: 50 MHz in → 100 MHz out
# The Amaranth Verilog uses clk_in as the raw oscillator input.
# Instantiate an MMCM wrapper in the XDC-driven way — Vivado infers it
# from the create_clock + MMCM IP if you prefer; or insert a hand-written
# MMCM_BASE primitive in the wrapper (see note in wukong_xc7a100t.py).
#
# For a quick Yosys/nextpnr-xilinx flow, replace clk_in with a direct
# ClockDomain connection and skip the MMCM.

launch_runs synth_1 -jobs 4
wait_on_run synth_1

launch_runs impl_1 -to_step write_bitstream -jobs 4
wait_on_run impl_1

set BIT $OUTDIR/$PROJ_NAME.runs/impl_1/top.bit
if {[file exists $BIT]} {
    file copy -force $BIT $OUTDIR/${PROJ_NAME}.bit
    puts "\n=== Bitstream written: $OUTDIR/${PROJ_NAME}.bit ==="
} else {
    puts "\n=== ERROR: bitstream not found at $BIT ==="
    exit 1
}

close_project
