#!/usr/bin/env python3
"""
scripts/patch_sapphire_init.py

Replace $readmemb calls (or existing inline assignments) in sapphire.v with
explicit Verilog initial-block assignments so EFX_MAP can embed firmware bytes
in the BRAM INITVAL_ parameters during synthesis.

EFX_MAP on Efinix Titanium ignores $readmemb file references (treats them
as simulation-only) but DOES honour explicit `mem[i] = N;` assignments in
initial blocks.  Without this patch, the system_ramA appears zero-initialised
to EFX_MAP, which then eliminates it entirely via optimize-zero-init-rom,
leaving the CPU bus hardwired to 0 and the firmware never executing.

The script handles two cases automatically:
  1. Virgin sapphire.v  — contains $readmemb(...) calls; replaces each with
                          inline assignments.
  2. Already-patched    — inline assignments already present from a previous
                          run; replaces them with fresh values from the
                          current symbol files.

Usage (run from repo root):
    python3 scripts/patch_sapphire_init.py \\
        hardware/soc_combined/sapphire.v \\
        hardware/soc_combined/EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol0.bin \\
        hardware/soc_combined/EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol1.bin \\
        hardware/soc_combined/EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol2.bin \\
        hardware/soc_combined/EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol3.bin

Or via Makefile shortcut (from hardware/soc_combined/):
    make patch_sapphire

The script edits sapphire.v in-place.  Re-run every time the firmware
changes, then re-synthesise.
"""

import sys
import re

SYMBOL_NAMES = [
    "EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol0.bin",
    "EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol1.bin",
    "EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol2.bin",
    "EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol3.bin",
]
RAM_VARS = ["ram_symbol0", "ram_symbol1", "ram_symbol2", "ram_symbol3"]


def read_symbol_bin(path):
    """
    Read a $readmemb binary file.

    Each non-empty, non-comment line is a binary string (e.g. "00010111")
    representing one 8-bit word.  Returns list of int.
    """
    values = []
    with open(path, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("//") or line.startswith("@"):
                continue
            values.append(int(line, 2))
    return values


def gen_assignments(var_name, values):
    """
    Generate Verilog initial-block assignments for one byte lane.

    Skips entries that are zero — EFX_RAM10 INIT_ defaults to 0,
    so only non-zero bytes need explicit assignment.  Always emits the
    very first entry (address 0) to prevent the whole block being
    optimised away as empty.
    """
    lines = []
    for i, v in enumerate(values):
        if v != 0 or i == 0:
            lines.append(f"        {var_name}[{i}] = 8'h{v:02X};")
    return "\n".join(lines)


def patch_lane(content, var, fname, assignments, lane_idx):
    """
    Replace either a $readmemb call or existing inline assignments for one lane.

    Returns (new_content, method_used) where method_used is 'readmemb' or 'inline'.
    Raises SystemExit if neither pattern is found.
    """
    # ── Case 1: virgin sapphire.v still has $readmemb ────────────────────────
    pattern_rmb = (
        r'\$readmemb\("'
        + re.escape(fname)
        + r'",'
        + r'\s*'
        + re.escape(var)
        + r"\);"
    )
    new_content, n = re.subn(pattern_rmb, assignments, content)
    if n > 0:
        print(f"  Replaced $readmemb symbol{lane_idx} → {assignments.count(chr(10)) + 1} assignments")
        return new_content, "readmemb"

    # ── Case 2: already-patched — inline assignments present ─────────────────
    # Match one or more consecutive assignment lines for this variable,
    # possibly with leading whitespace and any hex value.
    pattern_inline = (
        r"(?:[ \t]+"
        + re.escape(var)
        + r"\[\d+\] = 8'h[0-9A-Fa-f]{2};\n)+"
    )
    new_content, n = re.subn(pattern_inline, assignments + "\n", content)
    if n > 0:
        print(f"  Updated inline symbol{lane_idx} → {assignments.count(chr(10)) + 1} assignments  (was already-patched)")
        return new_content, "inline"

    # ── Neither found ─────────────────────────────────────────────────────────
    print(
        f"ERROR: neither $readmemb nor inline assignments for {var} found in sapphire.v",
        file=sys.stderr,
    )
    print(
        "  Possible causes:\n"
        "    • sapphire.v is a different version of the Efinix IP\n"
        "    • The ram variable is named differently in this version\n"
        "    • The file was not generated by the Efinix Sapphire SoC IP\n"
        "  Grep for 'ram_symbol' in sapphire.v to inspect the current state.",
        file=sys.stderr,
    )
    sys.exit(1)


def main():
    if len(sys.argv) < 6:
        print(
            "Usage: patch_sapphire_init.py sapphire.v "
            "symbol0.bin symbol1.bin symbol2.bin symbol3.bin",
            file=sys.stderr,
        )
        sys.exit(1)

    sapphire_path = sys.argv[1]
    bin_paths = sys.argv[2:6]

    lanes = []
    for i, path in enumerate(bin_paths):
        print(f"  Reading symbol{i}: {path} ...", end=" ", flush=True)
        v = read_symbol_bin(path)
        nonzero = sum(1 for x in v if x)
        print(f"{len(v)} entries, {nonzero} non-zero")
        lanes.append(v)

    with open(sapphire_path, "r") as f:
        content = f.read()

    original_len = len(content)

    for i in range(4):
        var = RAM_VARS[i]
        fname = SYMBOL_NAMES[i]
        assignments = gen_assignments(var, lanes[i])
        content, _ = patch_lane(content, var, fname, assignments, i)

    with open(sapphire_path, "w") as f:
        f.write(content)

    delta = len(content) - original_len
    print(
        f"\nPatched {sapphire_path}  "
        f"({delta:+,} chars, {len(content):,} total)"
    )
    print(
        "\nNext steps:\n"
        "  1. bash work_syn/run_efx_map.sh   (re-synthesise)\n"
        "  2. bash work_pnr/run_efx_pnr.sh   (place & route — generates .hex)\n"
        "  3. sudo ~/oss-cad-suite/bin/openFPGALoader "
        "-b titanium_ti60_f225_jtag -f outflow/church_soc_cm.hex\n"
    )


if __name__ == "__main__":
    main()
